import { ReviewResult } from "../../types/types";
export function renderReview(result: ReviewResult): string {
  if (result.reviews.length === 0) {
    return `<!-- lorica-review -->

## 🤖 Lorica AI Code Review

✅ **No actionable issues found.**

${result.summary}

<sub>Generated by Lorica.</sub>`;
  }

  const findings = result.reviews
    .map((review, index) => {
      const severity =
        review.severity === "critical"
          ? "🔴"
          : review.severity === "high"
            ? "🟠"
            : review.severity === "medium"
              ? "🟡"
              : "🔵";

      return `### ${severity} ${index + 1}. \`${review.filePath}:${review.lineNumber}\`

**Severity:** \`${review.severity}\`  
**Category:** \`${review.category}\`

\`\`\`
${review.code}
\`\`\`

**Issue**

${review.comment}

${
  review.suggestion
    ? `**Suggested fix**

${review.suggestion}`
    : ""
}`;
    })
    .join("\n\n---\n\n");

  return `<!-- lorica-review -->

## 🤖 Lorica AI Code Review

${result.summary}

${findings}

---

<sub>Generated by Lorica.</sub>`;
}